/**
 * Configuration conversationnelle du chatbot CPTS Ouest Gironde.
 *
 * Dérogation à CLAUDE.md règle "données en JSON" :
 * Ce fichier contient les ressources, mots-clés et nodes en TypeScript natif
 * plutôt qu'en JSON externalisé dans app/data/. Choix conscient pour bénéficier
 * du typage strict sur les références croisées (nextNodeId, actionResourceIds,
 * resourceId) qui éviterait des erreurs runtime invisibles dans un JSON.
 *
 * Un refacto vers JSON + Zod est possible en V2 si :
 * - La config grossit significativement
 * - Un non-développeur (Kheira, équipe CPTS) doit éditer le contenu sans toucher
 *   au code
 */
import type { ChatbotConfig, QuickReply } from "./types"

const mainQuickReplies: QuickReply[] = [
  {
    id: "qr-medecin-traitant",
    label: "Trouver un médecin traitant",
    value: "medecin traitant",
    nextNodeId: "medecin-traitant",
  },
  {
    id: "qr-urgences",
    label: "Urgences et numéros utiles",
    value: "urgences",
    nextNodeId: "urgences",
  },
  {
    id: "qr-sante-mentale",
    label: "Santé mentale",
    value: "sante mentale",
    nextNodeId: "sante-mentale",
  },
  {
    id: "qr-annuaire",
    label: "Trouver un professionnel",
    value: "annuaire",
    nextNodeId: "annuaire",
  },
  {
    id: "qr-presentation-cpts",
    label: "Comprendre la CPTS",
    value: "presentation cpts",
    nextNodeId: "presentation-node",
  },
  {
    id: "qr-mon-espace-sante",
    label: "Mon Espace Santé",
    value: "mon espace sante",
    nextNodeId: "mon-espace-sante-node",
  },
  {
    id: "qr-pro",
    label: "Ressources professionnels",
    value: "ressources professionnels",
    nextNodeId: "professionnels",
  },
  {
    id: "qr-supports",
    label: "Commander des supports",
    value: "commander des supports",
    nextNodeId: "supports",
  },
  {
    id: "qr-formations",
    label: "Formations CPTS",
    value: "formations cpts",
    nextNodeId: "formations",
  },
  {
    id: "qr-prevention",
    label: "Prévention santé familiale",
    value: "prevention",
    nextNodeId: "prevention",
  },
  {
    id: "qr-faq",
    label: "FAQ / questions fréquentes",
    value: "faq",
    nextNodeId: "faq",
  },
]

const restartQuickReply: QuickReply = {
  id: "qr-retour-accueil",
  label: "Revenir au menu principal",
  value: "menu principal",
  nextNodeId: "start",
}

const errorPageQuickReplies: QuickReply[] = [
  {
    id: "qr-medecin-traitant",
    label: "Trouver un médecin traitant",
    value: "medecin traitant",
    nextNodeId: "medecin-traitant",
  },
  {
    id: "qr-annuaire",
    label: "Voir l'annuaire",
    value: "annuaire",
    nextNodeId: "annuaire",
  },
  {
    id: "qr-page-accueil",
    label: "Page d'accueil",
    value: "page d accueil",
    actionResourceIds: ["accueil"],
  },
  {
    id: "qr-contact-cpts",
    label: "Contacter la CPTS",
    value: "contacter la cpts",
    actionResourceIds: ["contact-email", "coordonnees"],
  },
]

export const chatbotConfig: ChatbotConfig = {
  resources: {
    accueil: {
      id: "accueil",
      type: "internal",
      title: "Page d'accueil",
      description: "Retour à la page d'accueil du site CPTS Ouest Gironde.",
      href: "/",
    },
    "medecin-traitant": {
      id: "medecin-traitant",
      type: "internal",
      title: "Avez-vous un médecin traitant ?",
      description: "Parcours et informations pour trouver un médecin traitant.",
      audience: "patient",
      href: "/patients/medecin-traitant",
    },
    "patients-medecin-traitant": {
      id: "patients-medecin-traitant",
      type: "internal",
      title: "Comment trouver et déclarer son médecin traitant",
      description:
        "Démarches, formulaire et lien vers l'annuaire santé Ameli pour déclarer votre médecin traitant.",
      audience: "patient",
      href: "/patients/medecin-traitant",
    },
    annuaire: {
      id: "annuaire",
      type: "internal",
      title: "Annuaire des professionnels de santé",
      description: "Rechercher un professionnel selon votre besoin.",
      audience: "patient",
      href: "/patients/annuaire",
    },
    presentation: {
      id: "presentation",
      type: "internal",
      title: "Présentation de la CPTS",
      description: "Comprendre ce qu'est la CPTS, son organisation et ses missions.",
      href: "/presentation",
    },
    coordonnees: {
      id: "coordonnees",
      type: "internal",
      title: "Coordonnées utiles",
      description: "Tous les contacts essentiels pour urgences et soins non programmés.",
      audience: "patient",
      href: "/patients/coordonnees",
    },
    "symptomes-douleur": {
      id: "symptomes-douleur",
      type: "internal",
      title: "Douleur ou symptôme physique",
      description: "Orientation vers médecin traitant, SAMU ou pharmacie de garde selon l'intensité.",
      audience: "patient",
      href: "/patients/coordonnees",
    },
    "mon-espace-sante": {
      id: "mon-espace-sante",
      type: "internal",
      title: "Mon Espace de Santé",
      description:
        "Espace numérique personnel pour stocker, consulter et partager vos documents et données de santé en sécurité.",
      audience: "patient",
      href: "/patients/mon-espace-sante",
    },
    "patients-tuto-espace-sante": {
      id: "patients-tuto-espace-sante",
      type: "internal",
      title: "Tutoriel Mon Espace Santé",
      description:
        "Vidéos pas à pas pour créer, activer et utiliser Mon Espace Santé depuis un ordinateur ou un téléphone.",
      audience: "patient",
      href: "/patients/mon-espace-sante/tuto-espace-sante",
    },
    "sante-mentale": {
      id: "sante-mentale",
      type: "internal",
      title: "Ressources santé mentale",
      description: "Aides, articles et outils sur la santé mentale.",
      href: "/sante-mental",
    },
    "sante-mentale-jeunes": {
      id: "sante-mentale-jeunes",
      type: "internal",
      title: "Santé mentale des jeunes",
      description: "Ressources spécifiques pour les jeunes et leurs proches.",
      audience: "patient",
      href: "/prevention/sante-familiale/sante-mentale-des-jeunes",
    },
    "sm-face-aux-violences": {
      id: "sm-face-aux-violences",
      type: "internal",
      title: "Face aux violences, vous n'êtes pas seules",
      description: "Information et orientation pour les victimes de violences.",
      href: "/prevention/sante-familiale/face-aux-violences",
      audience: "patient",
      isSensitive: true,
      sensitivityCategory: "violence",
    },
    "sm-pro-approches": {
      id: "sm-pro-approches",
      type: "internal",
      title: "Professionnels et approches en santé mentale",
      description: "Comprendre les différents professionnels et approches thérapeutiques.",
      href: "/sante-mentale-professionnels-et-approches",
    },
    "prevention-familiale": {
      id: "prevention-familiale",
      type: "internal",
      title: "Articles santé familiale",
      description: "Vaccination, dépistage, sommeil, prévention du quotidien.",
      audience: "patient",
      href: "/prevention/sante-familiale",
    },
    "prevention-vaccinations": {
      id: "prevention-vaccinations",
      type: "internal",
      title: "Campagnes de vaccination",
      description: "Informations et articles de prévention sur les vaccinations.",
      audience: "patient",
      href: "/prevention/sante-familiale",
    },
    "memos-suivi": {
      id: "memos-suivi",
      type: "internal",
      title: "Fiches de suivi",
      description: "Ressources de suivi et prévention disponibles pour les patients.",
      audience: "patient",
      href: "/prevention/memos-suivi",
    },
    "ms-diabete": {
      id: "ms-diabete",
      type: "internal",
      title: "Mémo suivi - Diabète",
      description: "Ouvrir le mémo de suivi dédié au diabète.",
      audience: "patient",
      href: "/prevention/memos-suivi?openMemo=diabete",
    },
    "ms-hypertension": {
      id: "ms-hypertension",
      type: "internal",
      title: "Mémo suivi - Hypertension artérielle",
      description: "Ouvrir le mémo de suivi dédié à l'hypertension artérielle.",
      audience: "patient",
      href: "/prevention/memos-suivi?openMemo=hypertension",
    },
    "ms-insuffisance-cardiaque": {
      id: "ms-insuffisance-cardiaque",
      type: "internal",
      title: "Mémo suivi - Insuffisance cardiaque",
      description: "Article de suivi dédié à l'insuffisance cardiaque.",
      audience: "patient",
      href: "/prevention/memos-suivi?openMemo=insuffisance-cardiaque",
    },
    "ms-grossesse": {
      id: "ms-grossesse",
      type: "internal",
      title: "Mémo suivi - Grossesse",
      description: "Ouvrir le mémo de suivi dédié à la grossesse.",
      audience: "patient",
      href: "/prevention/memos-suivi?openMemo=grossesse",
    },
    "ms-prevention-sexuelle": {
      id: "ms-prevention-sexuelle",
      type: "internal",
      title: "Mémo suivi - Prévention santé sexuelle",
      description: "Ouvrir le mémo prévention santé sexuelle.",
      audience: "patient",
      href: "/prevention/memos-suivi?openMemo=prevention-sexuelle",
    },
    "ms-bon-usage-systeme-sante": {
      id: "ms-bon-usage-systeme-sante",
      type: "internal",
      title: "Mémo suivi - Bon usage du système de santé",
      description: "Ouvrir le mémo bon usage du système de santé.",
      audience: "patient",
      href: "/prevention/memos-suivi?openMemo=bon-usage",
    },
    "ms-parent-planner": {
      id: "ms-parent-planner",
      type: "internal",
      title: "Mémo suivi - Parent Planner",
      description: "Ouvrir le mémo Parent Planner.",
      audience: "patient",
      href: "/prevention/memos-suivi?openMemo=parent-planner",
    },
    "sf-insomnie": {
      id: "sf-insomnie",
      type: "internal",
      title: "Santé familiale - Insomnie",
      description: "Comprendre l'insomnie et les solutions de prise en charge.",
      audience: "patient",
      href: "/prevention/sante-familiale/insomnie",
    },
    "sf-endometriose": {
      id: "sf-endometriose",
      type: "internal",
      title: "Santé familiale - Endométriose",
      description: "Comprendre les signes, le diagnostic et la prise en charge de l'endométriose.",
      audience: "patient",
      href: "/prevention/sante-familiale/endometriose-depistage-prise-en-charge",
    },
    "sf-mois-sans-tabac-2025": {
      id: "sf-mois-sans-tabac-2025",
      type: "internal",
      title: "Santé familiale - Mois sans tabac 2025",
      description: "Article de prévention et d'accompagnement à l'arrêt du tabac.",
      audience: "patient",
      href: "/prevention/sante-familiale/mois-sans-tabac-novembre-2025",
    },
    "sf-movember-2026": {
      id: "sf-movember-2026",
      type: "internal",
      title: "Santé familiale - Movember 2026",
      description: "Campagne de prévention santé masculine.",
      audience: "patient",
      href: "/prevention/sante-familiale/movember-2026",
    },
    "sf-octobre-rose-2025": {
      id: "sf-octobre-rose-2025",
      type: "internal",
      title: "Santé familiale - Octobre rose 2025",
      description: "Campagne de sensibilisation et dépistage du cancer du sein.",
      audience: "patient",
      href: "/prevention/sante-familiale/octobre-rose-2025",
    },
    "sf-mars-bleu-2026": {
      id: "sf-mars-bleu-2026",
      type: "internal",
      title: "Santé familiale - Mars bleu 2026",
      description: "Prévention du cancer colorectal et dépistage organisé.",
      audience: "patient",
      href: "/prevention/sante-familiale/prevention-cancer-colorectal-mars-bleu-2026",
    },
    "sf-vaccination-covid-2025": {
      id: "sf-vaccination-covid-2025",
      type: "internal",
      title: "Santé familiale - Vaccination anti-COVID 2025",
      description: "Informations de prévention sur la vaccination anti-COVID.",
      audience: "patient",
      href: "/prevention/sante-familiale/vaccination-anti-covid-2025",
    },
    "sf-vaccination-grippe-2025": {
      id: "sf-vaccination-grippe-2025",
      type: "internal",
      title: "Santé familiale - Vaccination antigrippale 2025",
      description: "Informations de prévention sur la vaccination contre la grippe.",
      audience: "patient",
      href: "/prevention/sante-familiale/vaccination-anti-grippale-2025",
    },
    "sf-papillomavirus": {
      id: "sf-papillomavirus",
      type: "internal",
      title: "Santé familiale - Vaccination papillomavirus",
      description: "Informations sur la vaccination contre le papillomavirus et la campagne scolaire.",
      audience: "patient",
      href: "/prevention/sante-familiale/vaccination-papillomavirus-campagne-scolaire-2026",
    },
    "sf-canicule": {
      id: "sf-canicule",
      type: "internal",
      title: "Canicule — les bons gestes face aux fortes chaleurs",
      description: "Conseils pour se protéger pendant les fortes chaleurs : hydratation, fraîcheur, vigilance pour les personnes fragiles et registre canicule.",
      audience: "patient",
      href: "/prevention/sante-familiale/canicule",
    },
    "sf-chute-personne-agee": {
      id: "sf-chute-personne-agee",
      type: "internal",
      title: "Chute de la personne âgée — comment la prévenir",
      description: "Prévenir les chutes des seniors : aménagement du logement, bons réflexes au quotidien et surveillance de la santé.",
      audience: "patient",
      href: "/prevention/sante-familiale/chute-personne-agee",
    },
    "sf-sante-voyage": {
      id: "sf-sante-voyage",
      type: "internal",
      title: "Santé en voyage — recommandations essentielles",
      description: "Préparer un voyage : consultation, vaccins, trousse médicale, paludisme, eau, transports, altitude, décalage horaire et profils particuliers.",
      audience: "patient",
      href: "/prevention/sante-familiale/sante-voyage",
    },
    "etp-apnee-sommeil": {
      id: "etp-apnee-sommeil",
      type: "internal",
      title: "Éducation thérapeutique - Syndrome d'apnée du sommeil",
      description: "Ressource dédiée au syndrome d'apnée du sommeil.",
      href: "/prevention/education-therapeutique/syndrome-apnee-sommeil",
    },
    "etp-ateliers": {
      id: "etp-ateliers",
      type: "internal",
      title: "Éducation thérapeutique - Ateliers du territoire",
      description: "Structures et modalités d'accès aux ateliers d'éducation thérapeutique.",
      href: "/prevention/education-therapeutique/ateliers-education-therapeutique",
    },
    "sante-mentale-annuaire": {
      id: "sante-mentale-annuaire",
      type: "internal",
      title: "Annuaire santé mentale",
      description: "Accès à l'annuaire santé mentale (ouverture directe de l'annuaire).",
      href: "/sante-mental?open=annuaire",
    },
    "pro-adhesion": {
      id: "pro-adhesion",
      type: "internal",
      title: "Adhérer à la CPTS",
      description: "Page d'adhésion des professionnels à la CPTS.",
      audience: "pro",
      href: "/professionnels/adhesion",
    },
    "espace-pro": {
      id: "espace-pro",
      type: "internal",
      title: "Espace professionnels de santé",
      description: "Outils, supports et formations réservés aux professionnels",
      audience: "pro",
      href: "/professionnels",
    },
    "pro-actions-outils": {
      id: "pro-actions-outils",
      type: "internal",
      title: "Nos actions & vos outils (professionnels)",
      description: "Toutes les ressources et outils destinés aux professionnels de santé.",
      audience: "pro",
      href: "/professionnels/actions-outils",
    },
    "pro-dispositifs-territoire": {
      id: "pro-dispositifs-territoire",
      type: "internal",
      title: "Dispositifs du territoire CPTS",
      description:
        "Ressources santé mentale pour les professionnels : dispositifs du territoire, orientation psychiatrie et RCP psy.",
      audience: "pro",
      href: "/professionnels/actions-outils/les-dispositifs-du-territoire",
    },
    "pro-supports": {
      id: "pro-supports",
      type: "internal",
      title: "Commander des supports",
      description:
        "Page de commande des supports pour adhérents. La demande est envoyée par email à la coordinatrice CPTS, puis impression et livraison.",
      audience: "pro",
      href: "/professionnels/supports",
    },
    "pro-formations": {
      id: "pro-formations",
      type: "internal",
      title: "Formations CPTS",
      description: "Formations à venir et passées, avec possibilité d'inscription.",
      audience: "pro",
      href: "/professionnels/formations",
    },
    "ao-questionnaire-medecin": {
      id: "ao-questionnaire-medecin",
      type: "external",
      title: "Questionnaire MÉDECIN - Patient sans médecin traitant",
      audience: "pro",
      href: "/actions-outils/medecin-traitan/Questionnaire-MEDECIN-Patient-sans-MT-A-TELECHARGER.pdf",
    },
    "ao-questionnaire-paramedical": {
      id: "ao-questionnaire-paramedical",
      type: "external",
      title: "Questionnaire PARAMÉDICAL - Patient sans médecin traitant",
      audience: "pro",
      href: "/actions-outils/medecin-traitan/Patient-sans-MT-Questionnaire-PARAMED-nov-23.pdf",
    },
    "ao-formulaire-mas": {
      id: "ao-formulaire-mas",
      type: "external",
      title: "Formulaire MAS",
      audience: "pro",
      href: "/actions-outils/Formulaire-MAS-a-telecharger.pdf",
    },
    "ao-affiche-pharmacies": {
      id: "ao-affiche-pharmacies",
      type: "external",
      title: "Pharmacies participantes (SNP)",
      audience: "pro",
      href: "/actions-outils/Affiche-Pharmacies-CPTS-OG.pdf",
    },
    "ao-questions-psy": {
      id: "ao-questions-psy",
      type: "external",
      title: "Questions Psy",
      audience: "pro",
      href: "/actions-outils/sante-mentale/Questions-Psy.pdf",
    },
    "ao-emsi2": {
      id: "ao-emsi2",
      type: "external",
      title: "emsi²",
      audience: "pro",
      href: "/actions-outils/sante-mentale/emsi%C2%B2.pdf",
    },
    "ao-reponse-psy": {
      id: "ao-reponse-psy",
      type: "external",
      title: "Réponse Psy",
      audience: "pro",
      href: "/actions-outils/sante-mentale/flyer-Reponse-Psy.pdf",
    },
    "ao-livret-mss": {
      id: "ao-livret-mss",
      type: "external",
      title: "Livret MSS",
      audience: "pro",
      href: "/actions-outils/livret-MSS-.pdf",
    },
    "ao-poletp": {
      id: "ao-poletp",
      type: "external",
      title: "Pôle ETP",
      audience: "pro",
      href: "https://www.poletpna.fr/",
    },
    "ao-maison-nutrition": {
      id: "ao-maison-nutrition",
      type: "external",
      title: "Maison Nutrition Diabète Coeur",
      audience: "pro",
      href: "https://www.maisonnutrition33.com/",
    },
    "ao-medprev": {
      id: "ao-medprev",
      type: "external",
      title: "Campagne Medprev",
      audience: "pro",
      href: "https://medprev.org/",
    },
    "ao-mots": {
      id: "ao-mots",
      type: "external",
      title: "Association MOTS",
      audience: "pro",
      href: "https://www.association-mots.org/",
    },
    faq: {
      id: "faq",
      type: "internal",
      title: "FAQ",
      description: "Réponses aux questions les plus fréquentes.",
      href: "/faq",
    },
    "contact-email": {
      id: "contact-email",
      type: "email",
      title: "Contacter la CPTS par email",
      description: "Pour une demande générale ou une orientation complémentaire.",
      value: "info@cpts-ouest-gironde.fr",
    },
    "urgence-3114": {
      id: "urgence-3114",
      type: "phone",
      title: "Prévention suicide - 3114",
      description: "Numéro national 24h/24, 7j/7.",
      value: "3114",
      isSensitive: true,
      sensitivityCategory: "suicide",
    },
    "urgence-3919": {
      id: "urgence-3919",
      type: "phone",
      title: "Violences Femmes Info",
      description: "Anonyme, gratuit, 24h/24.",
      value: "3919",
      isSensitive: true,
      sensitivityCategory: "violence",
    },
    "urgence-17": {
      id: "urgence-17",
      type: "phone",
      title: "Police secours",
      description: "En cas de danger immédiat.",
      value: "17",
      isSensitive: true,
      sensitivityCategory: "violence",
    },
    "urgence-15": {
      id: "urgence-15",
      type: "phone",
      value: "15",
      title: "SAMU",
      description: "Urgences médicales 24h/24",
      isSensitive: true,
      sensitivityCategory: "danger-vital",
    },
    "pharmacie-garde": {
      id: "pharmacie-garde",
      type: "external",
      title: "Pharmacie de garde",
      description: "Rechercher la pharmacie de garde la plus proche.",
      href: "https://www.pharmaciedegarde.com/",
    },
  },
  keywordIndex: [
    { keyword: "medecin traitant", resourceId: "medecin-traitant", scoreBoost: 12 },
    { keyword: "recherche medecin", resourceId: "medecin-traitant" },
    { keyword: "docteur", resourceId: "medecin-traitant", scoreBoost: 10 },
    { keyword: "generaliste", resourceId: "medecin-traitant", scoreBoost: 10 },
    { keyword: "médecin généraliste", resourceId: "medecin-traitant", scoreBoost: 12 },
    { keyword: "toubib", resourceId: "medecin-traitant", scoreBoost: 8 },
    { keyword: "médecin de famille", resourceId: "medecin-traitant", scoreBoost: 12 },
    { keyword: "trouver un docteur", resourceId: "medecin-traitant", scoreBoost: 12 },
    { keyword: "pas de médecin", resourceId: "medecin-traitant", scoreBoost: 12 },
    { keyword: "sans médecin", resourceId: "medecin-traitant", scoreBoost: 12 },
    { keyword: "je cherche medecin", resourceId: "medecin-traitant", scoreBoost: 16 },
    { keyword: "je cherche docteur", resourceId: "medecin-traitant", scoreBoost: 16 },
    { keyword: "je cherche un toubib", resourceId: "medecin-traitant", scoreBoost: 14 },
    { keyword: "trouver medecin", resourceId: "medecin-traitant", scoreBoost: 16 },
    { keyword: "trouver docteur", resourceId: "medecin-traitant", scoreBoost: 16 },
    { keyword: "je n ai pas de medecin", resourceId: "medecin-traitant", scoreBoost: 18 },
    { keyword: "pas de medecin traitant", resourceId: "medecin-traitant", scoreBoost: 18 },
    { keyword: "besoin medecin", resourceId: "medecin-traitant", scoreBoost: 14 },
    { keyword: "comment avoir medecin", resourceId: "medecin-traitant", scoreBoost: 14 },
    { keyword: "comment trouver medecin", resourceId: "medecin-traitant", scoreBoost: 16 },
    { keyword: "il me faut docteur", resourceId: "medecin-traitant", scoreBoost: 14 },
    { keyword: "medecin generaliste", resourceId: "medecin-traitant", scoreBoost: 16 },
    { keyword: "docteur generaliste", resourceId: "medecin-traitant", scoreBoost: 14 },
    { keyword: "praticien", resourceId: "medecin-traitant", scoreBoost: 10 },
    { keyword: "doc", resourceId: "medecin-traitant", scoreBoost: 10 },
    { keyword: "medecin part a la retraite", resourceId: "medecin-traitant", scoreBoost: 22 },
    { keyword: "mon medecin arrete", resourceId: "medecin-traitant", scoreBoost: 20 },
    { keyword: "changer de medecin", resourceId: "medecin-traitant", scoreBoost: 18 },
    { keyword: "mon docteur prend sa retraite", resourceId: "medecin-traitant", scoreBoost: 22 },
    { keyword: "perdu mon medecin", resourceId: "medecin-traitant", scoreBoost: 18 },
    { keyword: "plus de medecin", resourceId: "medecin-traitant", scoreBoost: 18 },
    { keyword: "mon medecin part", resourceId: "medecin-traitant", scoreBoost: 20 },
    { keyword: "declarer medecin traitant", resourceId: "patients-medecin-traitant", scoreBoost: 18 },
    { keyword: "formulaire medecin traitant", resourceId: "patients-medecin-traitant", scoreBoost: 18 },
    { keyword: "demarche medecin traitant", resourceId: "patients-medecin-traitant", scoreBoost: 16 },
    { keyword: "comment declarer medecin", resourceId: "patients-medecin-traitant", scoreBoost: 80 },
    { keyword: "declaration assurance maladie", resourceId: "patients-medecin-traitant", scoreBoost: 14 },
    { keyword: "ameli medecin traitant", resourceId: "patients-medecin-traitant", scoreBoost: 16 },
    { keyword: "ameli medecin", resourceId: "patients-medecin-traitant", scoreBoost: 18 },
    { keyword: "ameli formulaire", resourceId: "patients-medecin-traitant", scoreBoost: 14 },
    { keyword: "formulaire ameli", resourceId: "patients-medecin-traitant", scoreBoost: 20 },
    { keyword: "formulaire ameli medecin", resourceId: "patients-medecin-traitant", scoreBoost: 22 },
    { keyword: "demarche ameli", resourceId: "patients-medecin-traitant", scoreBoost: 16 },
    { keyword: "declarer mon medecin", resourceId: "patients-medecin-traitant", scoreBoost: 22 },
    { keyword: "declaration medecin traitant", resourceId: "patients-medecin-traitant", scoreBoost: 22 },
    { keyword: "annuaire ameli", resourceId: "patients-medecin-traitant", scoreBoost: 14 },
    { keyword: "annuaire sante ameli", resourceId: "patients-medecin-traitant", scoreBoost: 14 },
    { keyword: "annuaire sante", resourceId: "patients-medecin-traitant", scoreBoost: 12 },
    { keyword: "trouver medecin demarche", resourceId: "patients-medecin-traitant", scoreBoost: 14 },
    { keyword: "papiers medecin traitant", resourceId: "patients-medecin-traitant", scoreBoost: 12 },
    { keyword: "comment changer medecin traitant", resourceId: "patients-medecin-traitant", scoreBoost: 16 },
    {
      keyword: "comment declarer medecin traitant assurance maladie",
      resourceId: "patients-medecin-traitant",
      scoreBoost: 90,
    },
    { keyword: "declarer medecin traitant assurance maladie", resourceId: "patients-medecin-traitant", scoreBoost: 84 },
    { keyword: "medecin traitant assurance maladie", resourceId: "patients-medecin-traitant", scoreBoost: 72 },
    { keyword: "medecin part retraite trouver autre", resourceId: "patients-medecin-traitant", scoreBoost: 30 },
    { keyword: "medecin prend retraite demarches", resourceId: "patients-medecin-traitant", scoreBoost: 24 },
    { keyword: "je cherche un medecin", resourceId: "patients-medecin-traitant", scoreBoost: 34 },
    { keyword: "je cherche medecin", resourceId: "patients-medecin-traitant", scoreBoost: 34 },
    { keyword: "trouver medecin", resourceId: "patients-medecin-traitant", scoreBoost: 34 },
    { keyword: "trouver docteur", resourceId: "patients-medecin-traitant", scoreBoost: 34 },
    { keyword: "il me faut un medecin", resourceId: "patients-medecin-traitant", scoreBoost: 30 },
    { keyword: "comment trouver medecin", resourceId: "patients-medecin-traitant", scoreBoost: 34 },
    { keyword: "ou trouver un medecin", resourceId: "patients-medecin-traitant", scoreBoost: 30 },
    { keyword: "cpts", resourceId: "presentation", scoreBoost: 6 },
    { keyword: "presentation cpts", resourceId: "presentation", scoreBoost: 12 },
    { keyword: "communaute professionnelle territoriale de sante", resourceId: "presentation", scoreBoost: 12 },
    { keyword: "patient sans medecin", resourceId: "ao-questionnaire-medecin" },
    { keyword: "questionnaire medecin", resourceId: "ao-questionnaire-medecin" },
    { keyword: "questionnaire paramedical", resourceId: "ao-questionnaire-paramedical" },

    { keyword: "annuaire", resourceId: "annuaire", scoreBoost: 8 },
    { keyword: "specialiste", resourceId: "annuaire" },
    { keyword: "professionnel", resourceId: "annuaire" },
    { keyword: "trouver un professionnel", resourceId: "annuaire", scoreBoost: 12 },
    { keyword: "liste des médecins", resourceId: "annuaire", scoreBoost: 10 },
    { keyword: "annuaire professionnels sante", resourceId: "annuaire", scoreBoost: 14 },
    { keyword: "annuaire cpts", resourceId: "annuaire", scoreBoost: 12 },
    { keyword: "professionnel pres de chez moi", resourceId: "annuaire", scoreBoost: 12 },
    { keyword: "chercher professionnel sante", resourceId: "annuaire", scoreBoost: 12 },
    { keyword: "liste professionnels sante", resourceId: "annuaire", scoreBoost: 12 },
    { keyword: "kiné", resourceId: "annuaire", scoreBoost: 8 },
    { keyword: "kinésithérapeute", resourceId: "annuaire", scoreBoost: 8 },
    { keyword: "infirmier", resourceId: "annuaire", scoreBoost: 8 },
    { keyword: "infirmière", resourceId: "annuaire", scoreBoost: 8 },
    { keyword: "dentiste", resourceId: "annuaire", scoreBoost: 8 },
    { keyword: "sage-femme", resourceId: "annuaire", scoreBoost: 8 },
    { keyword: "orthophoniste", resourceId: "annuaire", scoreBoost: 8 },
    { keyword: "podologue", resourceId: "annuaire", scoreBoost: 8 },
    { keyword: "ostéopathe", resourceId: "annuaire", scoreBoost: 8 },

    { keyword: "urgence", resourceId: "coordonnees", scoreBoost: 10 },
    { keyword: "samu", resourceId: "coordonnees" },
    { keyword: "15", resourceId: "coordonnees", scoreBoost: 8 },
    { keyword: "112", resourceId: "coordonnees" },
    { keyword: "sos médecin", resourceId: "coordonnees", scoreBoost: 10 },
    { keyword: "sos", resourceId: "coordonnees", scoreBoost: 8 },
    { keyword: "garde", resourceId: "coordonnees", scoreBoost: 8 },
    { keyword: "médecin de garde", resourceId: "coordonnees", scoreBoost: 12 },
    { keyword: "pharmacie de garde", resourceId: "pharmacie-garde", scoreBoost: 14 },
    { keyword: "coordonnees utiles", resourceId: "coordonnees", scoreBoost: 14 },
    { keyword: "contacts utiles", resourceId: "coordonnees", scoreBoost: 14 },
    { keyword: "numero utile", resourceId: "coordonnees", scoreBoost: 12 },
    { keyword: "numeros urgence", resourceId: "coordonnees", scoreBoost: 12 },
    { keyword: "qui appeler", resourceId: "coordonnees", scoreBoost: 8 },
    { keyword: "contact soins", resourceId: "coordonnees", scoreBoost: 10 },

    { keyword: "sante mentale", resourceId: "sante-mentale", scoreBoost: 9 },
    { keyword: "psychologue", resourceId: "sante-mentale-annuaire", scoreBoost: 12 },
    { keyword: "psy", resourceId: "sante-mentale-annuaire", scoreBoost: 12 },
    { keyword: "psychiatre", resourceId: "sante-mentale-annuaire", scoreBoost: 12 },
    { keyword: "annuaire sante mentale", resourceId: "sante-mentale-annuaire", scoreBoost: 16 },
    { keyword: "annuaire psy", resourceId: "sante-mentale-annuaire", scoreBoost: 12 },
    { keyword: "annuaire psychologue", resourceId: "sante-mentale-annuaire", scoreBoost: 14 },
    { keyword: "annuaire psychiatre", resourceId: "sante-mentale-annuaire", scoreBoost: 14 },
    { keyword: "chercher psy", resourceId: "sante-mentale-annuaire", scoreBoost: 10 },
    { keyword: "chercher psychologue", resourceId: "sante-mentale-annuaire", scoreBoost: 14 },
    { keyword: "ou consulter psy", resourceId: "sante-mentale-annuaire", scoreBoost: 14 },
    { keyword: "liste des psys", resourceId: "sante-mentale-annuaire", scoreBoost: 12 },
    { keyword: "psy disponible", resourceId: "sante-mentale-annuaire", scoreBoost: 12 },
    { keyword: "psy pres de chez moi", resourceId: "sante-mentale-annuaire", scoreBoost: 12 },
    { keyword: "depression", resourceId: "sante-mentale" },
    { keyword: "dépression", resourceId: "sante-mentale" },
    { keyword: "anxiété", resourceId: "sante-mentale" },
    { keyword: "angoisse", resourceId: "sante-mentale" },
    { keyword: "stress", resourceId: "sante-mentale" },
    { keyword: "burnout", resourceId: "sante-mentale", scoreBoost: 10 },
    { keyword: "mal-être", resourceId: "sante-mentale", scoreBoost: 10 },
    { keyword: "mal être", resourceId: "sante-mentale", scoreBoost: 10 },
    { keyword: "thérapie", resourceId: "sante-mentale", scoreBoost: 10 },
    { keyword: "aide psychologique", resourceId: "sante-mentale", scoreBoost: 12 },
    { keyword: "je deprime", resourceId: "sante-mentale", scoreBoost: 16 },
    { keyword: "je suis depressif", resourceId: "sante-mentale", scoreBoost: 16 },
    { keyword: "je suis depressive", resourceId: "sante-mentale", scoreBoost: 16 },
    { keyword: "je vais mal", resourceId: "sante-mentale", scoreBoost: 14 },
    { keyword: "je ne vais pas bien", resourceId: "sante-mentale", scoreBoost: 14 },
    { keyword: "ca ne va pas", resourceId: "sante-mentale", scoreBoost: 14 },
    { keyword: "j ai le moral a zero", resourceId: "sante-mentale", scoreBoost: 16 },
    { keyword: "j ai des pensees noires", resourceId: "sante-mentale", scoreBoost: 18 },
    { keyword: "je n ai plus envie", resourceId: "sante-mentale", scoreBoost: 16 },
    { keyword: "rien ne va", resourceId: "sante-mentale", scoreBoost: 14 },
    { keyword: "j ai besoin de parler", resourceId: "sante-mentale", scoreBoost: 16 },
    { keyword: "je suis stresse", resourceId: "sante-mentale", scoreBoost: 14 },
    { keyword: "crise d angoisse", resourceId: "sante-mentale", scoreBoost: 16 },
    { keyword: "epuise", resourceId: "sante-mentale", scoreBoost: 12 },
    { keyword: "epuisement", resourceId: "sante-mentale", scoreBoost: 12 },
    { keyword: "therapeute", resourceId: "sante-mentale", scoreBoost: 10 },
    { keyword: "consulter psy", resourceId: "sante-mentale", scoreBoost: 14 },
    { keyword: "suicide", resourceId: "urgence-3114", scoreBoost: 20 },
    { keyword: "suicidaire", resourceId: "urgence-3114", scoreBoost: 22 },
    { keyword: "suicidaires", resourceId: "urgence-3114", scoreBoost: 22 },
    { keyword: "pensees suicidaires", resourceId: "urgence-3114", scoreBoost: 30 },
    { keyword: "idees suicidaires", resourceId: "urgence-3114", scoreBoost: 30 },
    { keyword: "pensees noires", resourceId: "urgence-3114", scoreBoost: 20 },
    { keyword: "envie de mourir", resourceId: "urgence-3114", scoreBoost: 26 },
    { keyword: "je veux mourir", resourceId: "urgence-3114", scoreBoost: 28 },
    { keyword: "je veux en finir", resourceId: "urgence-3114", scoreBoost: 28 },
    { keyword: "en finir avec la vie", resourceId: "urgence-3114", scoreBoost: 28 },
    { keyword: "je ne veux plus vivre", resourceId: "urgence-3114", scoreBoost: 28 },
    { keyword: "plus envie de vivre", resourceId: "urgence-3114", scoreBoost: 26 },
    { keyword: "mettre fin a mes jours", resourceId: "urgence-3114", scoreBoost: 28 },
    { keyword: "mettre fin a ma vie", resourceId: "urgence-3114", scoreBoost: 28 },
    { keyword: "me suicider", resourceId: "urgence-3114", scoreBoost: 26 },
    { keyword: "je vais me suicider", resourceId: "urgence-3114", scoreBoost: 28 },
    { keyword: "je veux me tuer", resourceId: "urgence-3114", scoreBoost: 28 },
    { keyword: "me tuer", resourceId: "urgence-3114", scoreBoost: 22 },
    { keyword: "3114", resourceId: "urgence-3114", scoreBoost: 22 },
    { keyword: "sante mentale jeunes", resourceId: "sante-mentale-jeunes", scoreBoost: 12 },
    { keyword: "adolescent", resourceId: "sante-mentale-jeunes" },
    { keyword: "enfant", resourceId: "sante-mentale-jeunes", scoreBoost: 12 },
    { keyword: "lyceen", resourceId: "sante-mentale-jeunes", scoreBoost: 14 },
    { keyword: "etudiant", resourceId: "sante-mentale-jeunes", scoreBoost: 12 },
    { keyword: "mal etre adolescent", resourceId: "sante-mentale-jeunes", scoreBoost: 16 },
    { keyword: "harcelement scolaire", resourceId: "sante-mentale-jeunes", scoreBoost: 16 },
    { keyword: "questions psy", resourceId: "ao-questions-psy", scoreBoost: 10 },
    { keyword: "reponse psy", resourceId: "ao-reponse-psy", scoreBoost: 10 },
    { keyword: "emsi", resourceId: "ao-emsi2", scoreBoost: 8 },

    { keyword: "violence", resourceId: "sm-face-aux-violences", scoreBoost: 16 },
    { keyword: "violences", resourceId: "sm-face-aux-violences", scoreBoost: 16 },
    { keyword: "violences conjugales", resourceId: "sm-face-aux-violences", scoreBoost: 20 },
    { keyword: "violences familiales", resourceId: "sm-face-aux-violences", scoreBoost: 18 },
    { keyword: "victime", resourceId: "sm-face-aux-violences", scoreBoost: 14 },
    { keyword: "agression", resourceId: "sm-face-aux-violences", scoreBoost: 14 },
    { keyword: "agression sexuelle", resourceId: "sm-face-aux-violences", scoreBoost: 22 },
    // `viol` (4 chars) substring conflict avec "violet"/"violon"/"violation". Boost 2 :
    // CONTAINS 85+2=87 (sous le seuil sensible 96 même après aggregation +4 par fuzzy),
    // EXACT 120+2=122 (conserve la détection de "viol" seul).
    { keyword: "viol", resourceId: "sm-face-aux-violences", scoreBoost: 2 },
    // `violee` (6 chars) EXACT permet "je suis violée"/"violée" seul ; boost 6 maintient
    // CONTAINS+fuzzy sous le seuil sur "violet" via aggregation.
    { keyword: "violee", resourceId: "sm-face-aux-violences", scoreBoost: 6 },
    { keyword: "violees", resourceId: "sm-face-aux-violences", scoreBoost: 22 },
    { keyword: "subi un viol", resourceId: "sm-face-aux-violences", scoreBoost: 24 },
    { keyword: "victime de viol", resourceId: "sm-face-aux-violences", scoreBoost: 24 },
    { keyword: "j ai ete violee", resourceId: "sm-face-aux-violences", scoreBoost: 24 },
    { keyword: "viol conjugal", resourceId: "sm-face-aux-violences", scoreBoost: 22 },
    { keyword: "harcelement", resourceId: "sm-face-aux-violences", scoreBoost: 14 },
    { keyword: "maltraitance", resourceId: "sm-face-aux-violences", scoreBoost: 14 },
    { keyword: "abus", resourceId: "sm-face-aux-violences", scoreBoost: 10 },
    { keyword: "abus sexuel", resourceId: "sm-face-aux-violences", scoreBoost: 22 },
    { keyword: "abus sexuels", resourceId: "sm-face-aux-violences", scoreBoost: 22 },
    { keyword: "victime d abus", resourceId: "sm-face-aux-violences", scoreBoost: 22 },
    { keyword: "subi des abus", resourceId: "sm-face-aux-violences", scoreBoost: 22 },
    { keyword: "3919", resourceId: "sm-face-aux-violences", scoreBoost: 18 },
    { keyword: "on me frappe", resourceId: "sm-face-aux-violences", scoreBoost: 18 },
    { keyword: "il me frappe", resourceId: "sm-face-aux-violences", scoreBoost: 18 },
    { keyword: "elle me frappe", resourceId: "sm-face-aux-violences", scoreBoost: 18 },
    { keyword: "je suis battue", resourceId: "sm-face-aux-violences", scoreBoost: 20 },
    { keyword: "je suis battu", resourceId: "sm-face-aux-violences", scoreBoost: 20 },
    { keyword: "violence conjugale", resourceId: "sm-face-aux-violences", scoreBoost: 18 },
    { keyword: "violence dans le couple", resourceId: "sm-face-aux-violences", scoreBoost: 18 },
    { keyword: "violence familiale", resourceId: "sm-face-aux-violences", scoreBoost: 16 },

    { keyword: "3919", resourceId: "urgence-3919", scoreBoost: 20 },
    { keyword: "violence", resourceId: "urgence-3919", scoreBoost: 14 },
    { keyword: "violences", resourceId: "urgence-3919", scoreBoost: 14 },
    { keyword: "violences conjugales", resourceId: "urgence-3919", scoreBoost: 18 },
    { keyword: "violences femmes", resourceId: "urgence-3919", scoreBoost: 18 },
    { keyword: "je suis battue", resourceId: "urgence-3919", scoreBoost: 18 },
    { keyword: "je suis battu", resourceId: "urgence-3919", scoreBoost: 18 },
    { keyword: "on me frappe", resourceId: "urgence-3919", scoreBoost: 18 },
    { keyword: "il me frappe", resourceId: "urgence-3919", scoreBoost: 18 },
    { keyword: "elle me frappe", resourceId: "urgence-3919", scoreBoost: 18 },

    { keyword: "police secours", resourceId: "urgence-17", scoreBoost: 16 },
    { keyword: "danger immediat", resourceId: "urgence-17", scoreBoost: 16 },
    { keyword: "appeler 17", resourceId: "urgence-17", scoreBoost: 18 },
    { keyword: "police urgence", resourceId: "urgence-17", scoreBoost: 16 },
    { keyword: "intervention police", resourceId: "urgence-17", scoreBoost: 14 },

    { keyword: "ovaire", resourceId: "symptomes-douleur", scoreBoost: 16 },
    { keyword: "ovaires", resourceId: "symptomes-douleur", scoreBoost: 16 },
    { keyword: "ventre", resourceId: "symptomes-douleur", scoreBoost: 12 },
    { keyword: "abdomen", resourceId: "symptomes-douleur", scoreBoost: 14 },
    { keyword: "tete", resourceId: "symptomes-douleur", scoreBoost: 10 },
    { keyword: "dos", resourceId: "symptomes-douleur", scoreBoost: 10 },
    { keyword: "poitrine", resourceId: "symptomes-douleur", scoreBoost: 14 },
    { keyword: "jambe", resourceId: "symptomes-douleur", scoreBoost: 10 },
    { keyword: "bras", resourceId: "symptomes-douleur", scoreBoost: 10 },
    { keyword: "gorge", resourceId: "symptomes-douleur", scoreBoost: 12 },
    { keyword: "oreille", resourceId: "symptomes-douleur", scoreBoost: 12 },
    { keyword: "oeil", resourceId: "symptomes-douleur", scoreBoost: 12 },
    { keyword: "yeux", resourceId: "symptomes-douleur", scoreBoost: 12 },
    { keyword: "dent", resourceId: "symptomes-douleur", scoreBoost: 12 },
    { keyword: "articulation", resourceId: "symptomes-douleur", scoreBoost: 12 },
    { keyword: "genou", resourceId: "symptomes-douleur", scoreBoost: 12 },
    { keyword: "douleur", resourceId: "symptomes-douleur", scoreBoost: 14 },
    { keyword: "j'ai mal", resourceId: "symptomes-douleur", scoreBoost: 16 },
    { keyword: "ca fait mal", resourceId: "symptomes-douleur", scoreBoost: 14 },
    { keyword: "souffrance", resourceId: "symptomes-douleur", scoreBoost: 12 },
    { keyword: "fievre", resourceId: "symptomes-douleur", scoreBoost: 14 },
    { keyword: "vomissement", resourceId: "symptomes-douleur", scoreBoost: 14 },
    { keyword: "nausee", resourceId: "symptomes-douleur", scoreBoost: 12 },
    { keyword: "vertige", resourceId: "symptomes-douleur", scoreBoost: 12 },
    { keyword: "vertiges", resourceId: "symptomes-douleur", scoreBoost: 12 },
    { keyword: "malaise", resourceId: "symptomes-douleur", scoreBoost: 16 },
    { keyword: "essoufflement", resourceId: "symptomes-douleur", scoreBoost: 14 },
    { keyword: "palpitations", resourceId: "symptomes-douleur", scoreBoost: 14 },
    { keyword: "qui appeler douleur", resourceId: "symptomes-douleur", scoreBoost: 18 },
    { keyword: "mal au ventre", resourceId: "symptomes-douleur", scoreBoost: 18 },
    { keyword: "mal a la tete", resourceId: "symptomes-douleur", scoreBoost: 18 },
    { keyword: "douleur intense", resourceId: "symptomes-douleur", scoreBoost: 16 },
    { keyword: "douleur soudaine", resourceId: "symptomes-douleur", scoreBoost: 18 },
    { keyword: "migraine", resourceId: "symptomes-douleur", scoreBoost: 16 },
    { keyword: "grosse migraine", resourceId: "symptomes-douleur", scoreBoost: 16 },
    { keyword: "migraine depuis", resourceId: "symptomes-douleur", scoreBoost: 16 },
    { keyword: "j ai mal a la tete depuis", resourceId: "symptomes-douleur", scoreBoost: 16 },
    { keyword: "tete depuis 2 jours", resourceId: "symptomes-douleur", scoreBoost: 14 },
    { keyword: "migraine 2 jours", resourceId: "symptomes-douleur", scoreBoost: 16 },
    { keyword: "cephalee", resourceId: "symptomes-douleur", scoreBoost: 14 },
    { keyword: "maux de tete", resourceId: "symptomes-douleur", scoreBoost: 16 },
    { keyword: "courbatures", resourceId: "symptomes-douleur", scoreBoost: 12 },
    { keyword: "fatigue", resourceId: "symptomes-douleur", scoreBoost: 12 },
    { keyword: "epuisement", resourceId: "symptomes-douleur", scoreBoost: 14 },
    { keyword: "rhume", resourceId: "symptomes-douleur", scoreBoost: 12 },
    { keyword: "grippe", resourceId: "symptomes-douleur", scoreBoost: 14 },
    { keyword: "toux", resourceId: "symptomes-douleur", scoreBoost: 12 },
    { keyword: "angine", resourceId: "symptomes-douleur", scoreBoost: 12 },
    { keyword: "gastro", resourceId: "symptomes-douleur", scoreBoost: 14 },
    { keyword: "constipation", resourceId: "symptomes-douleur", scoreBoost: 12 },
    { keyword: "diarrhee", resourceId: "symptomes-douleur", scoreBoost: 14 },
    { keyword: "brulure", resourceId: "symptomes-douleur", scoreBoost: 14 },
    { keyword: "blessure", resourceId: "symptomes-douleur", scoreBoost: 14 },
    { keyword: "entorse", resourceId: "symptomes-douleur", scoreBoost: 14 },
    { keyword: "foulure", resourceId: "symptomes-douleur", scoreBoost: 14 },
    { keyword: "courbe", resourceId: "symptomes-douleur", scoreBoost: 10 },
    { keyword: "je tousse", resourceId: "symptomes-douleur", scoreBoost: 14 },
    { keyword: "j ai pris froid", resourceId: "symptomes-douleur", scoreBoost: 14 },
    { keyword: "j ai chope un rhume", resourceId: "symptomes-douleur", scoreBoost: 14 },
    { keyword: "je suis enrhume", resourceId: "symptomes-douleur", scoreBoost: 14 },
    { keyword: "j ai la grippe", resourceId: "symptomes-douleur", scoreBoost: 20 },
    { keyword: "je me suis fait mal", resourceId: "symptomes-douleur", scoreBoost: 16 },
    { keyword: "je me suis foule", resourceId: "symptomes-douleur", scoreBoost: 16 },
    { keyword: "je suis tombe", resourceId: "symptomes-douleur", scoreBoost: 14 },
    { keyword: "j ai des courbatures", resourceId: "symptomes-douleur", scoreBoost: 14 },
    { keyword: "je suis fatigue", resourceId: "symptomes-douleur", scoreBoost: 12 },
    { keyword: "douleur poitrine", resourceId: "urgence-15", scoreBoost: 20 },
    { keyword: "douleur thoracique", resourceId: "urgence-15", scoreBoost: 20 },
    { keyword: "douleur thorax", resourceId: "urgence-15", scoreBoost: 20 },
    { keyword: "j ai un malaise", resourceId: "urgence-15", scoreBoost: 18 },
    { keyword: "j ai fait un malaise", resourceId: "urgence-15", scoreBoost: 18 },
    { keyword: "je ne respire plus", resourceId: "urgence-15", scoreBoost: 20 },
    { keyword: "je ne respire pas bien", resourceId: "urgence-15", scoreBoost: 18 },
    { keyword: "douleur au coeur", resourceId: "urgence-15", scoreBoost: 20 },
    { keyword: "infarctus", resourceId: "urgence-15", scoreBoost: 20 },
    { keyword: "avc", resourceId: "urgence-15", scoreBoost: 20 },
    { keyword: "accident vasculaire", resourceId: "urgence-15", scoreBoost: 18 },
    { keyword: "il s evanouit", resourceId: "urgence-15", scoreBoost: 18 },
    { keyword: "elle s evanouit", resourceId: "urgence-15", scoreBoost: 18 },
    { keyword: "perte de connaissance", resourceId: "urgence-15", scoreBoost: 20 },
    { keyword: "il ne respire plus", resourceId: "urgence-15", scoreBoost: 20 },
    { keyword: "elle ne respire plus", resourceId: "urgence-15", scoreBoost: 20 },
    { keyword: "j etouffe", resourceId: "urgence-15", scoreBoost: 22 },
    { keyword: "je m etouffe", resourceId: "urgence-15", scoreBoost: 22 },
    { keyword: "etouffement", resourceId: "urgence-15", scoreBoost: 20 },
    { keyword: "il etouffe", resourceId: "urgence-15", scoreBoost: 22 },
    { keyword: "elle etouffe", resourceId: "urgence-15", scoreBoost: 22 },
    { keyword: "je n arrive plus a respirer", resourceId: "urgence-15", scoreBoost: 22 },
    { keyword: "j ai du mal a respirer", resourceId: "urgence-15", scoreBoost: 22 },
    { keyword: "j arrive plus a respirer", resourceId: "urgence-15", scoreBoost: 22 },
    { keyword: "je n arrive pas a respirer", resourceId: "urgence-15", scoreBoost: 22 },
    { keyword: "je vais mourir", resourceId: "urgence-15", scoreBoost: 20 },
    { keyword: "je perds connaissance", resourceId: "urgence-15", scoreBoost: 20 },
    { keyword: "il fait un malaise", resourceId: "urgence-15", scoreBoost: 20 },
    { keyword: "elle fait un malaise", resourceId: "urgence-15", scoreBoost: 20 },
    { keyword: "douleur dans la poitrine", resourceId: "urgence-15", scoreBoost: 22 },

    { keyword: "j ai mal", resourceId: "symptomes-douleur", scoreBoost: 16 },
    { keyword: "j ai des douleurs", resourceId: "symptomes-douleur", scoreBoost: 16 },
    { keyword: "mal partout", resourceId: "symptomes-douleur", scoreBoost: 14 },
    { keyword: "je souffre", resourceId: "symptomes-douleur", scoreBoost: 14 },
    { keyword: "je suis malade", resourceId: "symptomes-douleur", scoreBoost: 14 },
    { keyword: "je ne me sens pas bien", resourceId: "symptomes-douleur", scoreBoost: 14 },
    { keyword: "douleur depuis", resourceId: "symptomes-douleur", scoreBoost: 14 },
    { keyword: "mal depuis ce matin", resourceId: "symptomes-douleur", scoreBoost: 14 },
    { keyword: "mal depuis hier", resourceId: "symptomes-douleur", scoreBoost: 14 },
    { keyword: "mal depuis plusieurs jours", resourceId: "symptomes-douleur", scoreBoost: 14 },
    { keyword: "qui consulter", resourceId: "symptomes-douleur", scoreBoost: 12 },
    { keyword: "qui voir si mal", resourceId: "symptomes-douleur", scoreBoost: 14 },
    { keyword: "mal a l estomac", resourceId: "symptomes-douleur", scoreBoost: 16 },
    { keyword: "mal aux yeux", resourceId: "symptomes-douleur", scoreBoost: 16 },
    { keyword: "mal a l oreille", resourceId: "symptomes-douleur", scoreBoost: 16 },
    { keyword: "mal au dos", resourceId: "symptomes-douleur", scoreBoost: 16 },
    { keyword: "mal a la jambe", resourceId: "symptomes-douleur", scoreBoost: 16 },

    { keyword: "tcc", resourceId: "sm-pro-approches", scoreBoost: 14 },
    { keyword: "psychotherapie", resourceId: "sm-pro-approches", scoreBoost: 16 },
    { keyword: "psychanalyse", resourceId: "sm-pro-approches", scoreBoost: 14 },
    { keyword: "emdr", resourceId: "sm-pro-approches", scoreBoost: 14 },
    { keyword: "therapie", resourceId: "sm-pro-approches", scoreBoost: 12 },
    { keyword: "approches therapeutiques", resourceId: "sm-pro-approches", scoreBoost: 16 },
    { keyword: "professionnels sante mentale", resourceId: "sm-pro-approches", scoreBoost: 14 },
    { keyword: "difference psy", resourceId: "sm-pro-approches", scoreBoost: 14 },
    { keyword: "psychiatre ou psychologue", resourceId: "sm-pro-approches", scoreBoost: 16 },

    { keyword: "mon espace sante", resourceId: "mon-espace-sante", scoreBoost: 18 },
    { keyword: "mes", resourceId: "mon-espace-sante", scoreBoost: 8 },
    { keyword: "espace santé", resourceId: "mon-espace-sante", scoreBoost: 16 },
    { keyword: "dossier medical en ligne", resourceId: "mon-espace-sante", scoreBoost: 14 },
    { keyword: "carnet de santé numérique", resourceId: "mon-espace-sante", scoreBoost: 14 },
    { keyword: "carnet de sante numerique", resourceId: "mon-espace-sante", scoreBoost: 14 },
    { keyword: "dossier médical", resourceId: "mon-espace-sante", scoreBoost: 12 },
    { keyword: "dossier patient", resourceId: "mon-espace-sante", scoreBoost: 12 },
    { keyword: "dmp", resourceId: "mon-espace-sante", scoreBoost: 12 },
    { keyword: "ouvrir mon espace sante", resourceId: "mon-espace-sante", scoreBoost: 14 },
    { keyword: "application sante", resourceId: "mon-espace-sante" },
    { keyword: "documents de sante", resourceId: "mon-espace-sante", scoreBoost: 12 },
    { keyword: "messagerie sante", resourceId: "mon-espace-sante", scoreBoost: 12 },
    { keyword: "tuto espace sante", resourceId: "patients-tuto-espace-sante", scoreBoost: 18 },
    { keyword: "tutoriel espace sante", resourceId: "patients-tuto-espace-sante", scoreBoost: 18 },
    { keyword: "comment utiliser mon espace sante", resourceId: "patients-tuto-espace-sante", scoreBoost: 20 },
    { keyword: "comment ouvrir mon espace sante", resourceId: "patients-tuto-espace-sante", scoreBoost: 16 },
    { keyword: "aide espace sante", resourceId: "patients-tuto-espace-sante", scoreBoost: 14 },
    { keyword: "guide espace sante", resourceId: "patients-tuto-espace-sante", scoreBoost: 14 },
    { keyword: "activer mon espace sante", resourceId: "patients-tuto-espace-sante", scoreBoost: 16 },
    { keyword: "installer mon espace sante", resourceId: "patients-tuto-espace-sante", scoreBoost: 14 },

    { keyword: "prevention", resourceId: "prevention-familiale" },
    { keyword: "vaccination", resourceId: "prevention-familiale" },
    { keyword: "vaccin", resourceId: "prevention-familiale" },
    { keyword: "dépistage", resourceId: "prevention-familiale", scoreBoost: 8 },
    { keyword: "bilan de santé", resourceId: "prevention-familiale", scoreBoost: 8 },
    { keyword: "check-up", resourceId: "prevention-familiale", scoreBoost: 8 },
    { keyword: "memos suivi", resourceId: "memos-suivi", scoreBoost: 8 },
    { keyword: "fiches de suivi", resourceId: "memos-suivi", scoreBoost: 8 },
    { keyword: "comment suivre ma maladie", resourceId: "memos-suivi", scoreBoost: 14 },
    { keyword: "carnet de suivi", resourceId: "memos-suivi", scoreBoost: 14 },
    { keyword: "fiche memo", resourceId: "memos-suivi", scoreBoost: 12 },
    { keyword: "je suis diabetique", resourceId: "memos-suivi", scoreBoost: 12 },
    { keyword: "j ai du diabete", resourceId: "memos-suivi", scoreBoost: 12 },
    { keyword: "j ai de l hypertension", resourceId: "memos-suivi", scoreBoost: 12 },
    { keyword: "j ai du cholesterol", resourceId: "memos-suivi", scoreBoost: 12 },
    { keyword: "diabete", resourceId: "ms-diabete", scoreBoost: 14 },
    { keyword: "memo diabete", resourceId: "ms-diabete", scoreBoost: 14 },
    { keyword: "hypertension arterielle", resourceId: "ms-hypertension", scoreBoost: 14 },
    { keyword: "hta", resourceId: "ms-hypertension", scoreBoost: 10 },
    { keyword: "insuffisance cardiaque", resourceId: "ms-insuffisance-cardiaque", scoreBoost: 14 },
    { keyword: "memo insuffisance cardiaque", resourceId: "ms-insuffisance-cardiaque", scoreBoost: 14 },
    { keyword: "grossesse", resourceId: "ms-grossesse", scoreBoost: 12 },
    { keyword: "suivi grossesse", resourceId: "ms-grossesse", scoreBoost: 12 },
    { keyword: "prevention sexuelle", resourceId: "ms-prevention-sexuelle", scoreBoost: 16 },
    { keyword: "sante sexuelle", resourceId: "ms-prevention-sexuelle", scoreBoost: 14 },
    { keyword: "ist", resourceId: "ms-prevention-sexuelle", scoreBoost: 12 },
    { keyword: "hpv", resourceId: "ms-prevention-sexuelle", scoreBoost: 12 },
    { keyword: "contraception", resourceId: "ms-prevention-sexuelle", scoreBoost: 12 },
    { keyword: "systeme de sante", resourceId: "ms-bon-usage-systeme-sante", scoreBoost: 16 },
    { keyword: "bon usage du systeme de sante", resourceId: "ms-bon-usage-systeme-sante", scoreBoost: 16 },
    { keyword: "bon usage systeme", resourceId: "ms-bon-usage-systeme-sante", scoreBoost: 14 },
    { keyword: "parent planner", resourceId: "ms-parent-planner", scoreBoost: 12 },
    { keyword: "doudou liste", resourceId: "ms-parent-planner", scoreBoost: 12 },
    { keyword: "insomnie", resourceId: "sf-insomnie", scoreBoost: 12 },
    { keyword: "trouble du sommeil", resourceId: "sf-insomnie", scoreBoost: 10 },
    { keyword: "dormir", resourceId: "sf-insomnie", scoreBoost: 12 },
    { keyword: "nuit blanche", resourceId: "sf-insomnie", scoreBoost: 14 },
    { keyword: "reveil nocturne", resourceId: "sf-insomnie", scoreBoost: 14 },
    { keyword: "hygiene sommeil", resourceId: "sf-insomnie", scoreBoost: 14 },
    { keyword: "melatonine", resourceId: "sf-insomnie", scoreBoost: 12 },
    { keyword: "trouble sommeil", resourceId: "sf-insomnie", scoreBoost: 14 },
    { keyword: "je dors mal", resourceId: "sf-insomnie", scoreBoost: 14 },
    { keyword: "sommeil", resourceId: "sf-insomnie", scoreBoost: 8 },
    { keyword: "apnee du sommeil", resourceId: "etp-apnee-sommeil", scoreBoost: 16 },
    { keyword: "syndrome apnee sommeil", resourceId: "etp-apnee-sommeil", scoreBoost: 14 },
    { keyword: "apnee sommeil", resourceId: "etp-apnee-sommeil", scoreBoost: 14 },
    { keyword: "mois sans tabac", resourceId: "sf-mois-sans-tabac-2025", scoreBoost: 14 },
    { keyword: "tabac", resourceId: "sf-mois-sans-tabac-2025", scoreBoost: 10 },
    { keyword: "arret tabac", resourceId: "sf-mois-sans-tabac-2025", scoreBoost: 10 },
    { keyword: "sevrage tabagique", resourceId: "sf-mois-sans-tabac-2025", scoreBoost: 16 },
    { keyword: "nicotine", resourceId: "sf-mois-sans-tabac-2025", scoreBoost: 12 },
    { keyword: "cigarette", resourceId: "sf-mois-sans-tabac-2025", scoreBoost: 12 },
    { keyword: "vapote", resourceId: "sf-mois-sans-tabac-2025", scoreBoost: 10 },
    { keyword: "vapotage", resourceId: "sf-mois-sans-tabac-2025", scoreBoost: 10 },
    { keyword: "tabac info service", resourceId: "sf-mois-sans-tabac-2025", scoreBoost: 14 },
    { keyword: "arret de fumer", resourceId: "sf-mois-sans-tabac-2025", scoreBoost: 14 },
    { keyword: "movember", resourceId: "sf-movember-2026", scoreBoost: 16 },
    { keyword: "sante masculine", resourceId: "sf-movember-2026", scoreBoost: 12 },
    { keyword: "cancer prostate", resourceId: "sf-movember-2026", scoreBoost: 16 },
    { keyword: "cancer testicule", resourceId: "sf-movember-2026", scoreBoost: 14 },
    { keyword: "psa", resourceId: "sf-movember-2026", scoreBoost: 12 },
    { keyword: "urologie", resourceId: "sf-movember-2026", scoreBoost: 12 },
    { keyword: "octobre rose", resourceId: "sf-octobre-rose-2025", scoreBoost: 16 },
    { keyword: "cancer du sein", resourceId: "sf-octobre-rose-2025", scoreBoost: 12 },
    { keyword: "mammographie", resourceId: "sf-octobre-rose-2025", scoreBoost: 14 },
    { keyword: "depistage sein", resourceId: "sf-octobre-rose-2025", scoreBoost: 16 },
    { keyword: "auto-palpation", resourceId: "sf-octobre-rose-2025", scoreBoost: 12 },
    { keyword: "cancer sein", resourceId: "sf-octobre-rose-2025", scoreBoost: 16 },
    { keyword: "mars bleu", resourceId: "sf-mars-bleu-2026", scoreBoost: 16 },
    { keyword: "cancer colorectal", resourceId: "sf-mars-bleu-2026", scoreBoost: 14 },
    { keyword: "je veux me depister", resourceId: "prevention-familiale", scoreBoost: 14 },
    { keyword: "depistage cancer", resourceId: "prevention-familiale", scoreBoost: 14 },
    { keyword: "test de depistage", resourceId: "prevention-familiale", scoreBoost: 12 },
    { keyword: "je veux faire un controle", resourceId: "prevention-familiale", scoreBoost: 12 },
    { keyword: "controle preventif", resourceId: "prevention-familiale", scoreBoost: 12 },
    { keyword: "colo rectal", resourceId: "sf-mars-bleu-2026", scoreBoost: 12 },
    { keyword: "depistage colorectal", resourceId: "sf-mars-bleu-2026", scoreBoost: 12 },
    { keyword: "hemoccult", resourceId: "sf-mars-bleu-2026", scoreBoost: 14 },
    { keyword: "kit depistage colorectal", resourceId: "sf-mars-bleu-2026", scoreBoost: 16 },
    { keyword: "sang dans les selles", resourceId: "sf-mars-bleu-2026", scoreBoost: 16 },
    { keyword: "coloscopie", resourceId: "sf-mars-bleu-2026", scoreBoost: 14 },
    { keyword: "vaccination anti covid", resourceId: "sf-vaccination-covid-2025", scoreBoost: 14 },
    { keyword: "anti covid", resourceId: "sf-vaccination-covid-2025", scoreBoost: 10 },
    { keyword: "covid", resourceId: "sf-vaccination-covid-2025", scoreBoost: 8 },
    { keyword: "rappel covid", resourceId: "sf-vaccination-covid-2025", scoreBoost: 14 },
    { keyword: "dose rappel", resourceId: "sf-vaccination-covid-2025", scoreBoost: 12 },
    { keyword: "vaccin sars", resourceId: "sf-vaccination-covid-2025", scoreBoost: 10 },
    { keyword: "vaccin coronavirus", resourceId: "sf-vaccination-covid-2025", scoreBoost: 12 },
    { keyword: "vaccination anti grippale", resourceId: "sf-vaccination-grippe-2025", scoreBoost: 14 },
    { keyword: "vaccination grippe", resourceId: "sf-vaccination-grippe-2025", scoreBoost: 25 },
    { keyword: "ou se faire vacciner", resourceId: "sf-vaccination-grippe-2025", scoreBoost: 12 },
    { keyword: "comment se faire vacciner", resourceId: "sf-vaccination-grippe-2025", scoreBoost: 12 },
    { keyword: "pharmacie qui vaccine", resourceId: "sf-vaccination-grippe-2025", scoreBoost: 14 },
    { keyword: "se faire vacciner grippe", resourceId: "sf-vaccination-grippe-2025", scoreBoost: 16 },
    { keyword: "vaccin contre la grippe", resourceId: "sf-vaccination-grippe-2025", scoreBoost: 25 },
    { keyword: "vacciner contre la grippe", resourceId: "sf-vaccination-grippe-2025", scoreBoost: 25 },
    { keyword: "se faire piquer", resourceId: "sf-vaccination-grippe-2025", scoreBoost: 10 },
    { keyword: "rappel vaccin", resourceId: "prevention-familiale", scoreBoost: 10 },
    { keyword: "carnet de vaccination", resourceId: "prevention-familiale", scoreBoost: 12 },
    { keyword: "vaccin grippe", resourceId: "sf-vaccination-grippe-2025", scoreBoost: 22 },
    { keyword: "injection grippe", resourceId: "sf-vaccination-grippe-2025", scoreBoost: 12 },
    { keyword: "pharmacien vaccinateur", resourceId: "sf-vaccination-grippe-2025", scoreBoost: 12 },
    { keyword: "grippe", resourceId: "sf-vaccination-grippe-2025", scoreBoost: 8 },
    { keyword: "se faire vacciner", resourceId: "prevention-vaccinations", scoreBoost: 20 },

    { keyword: "papillomavirus", resourceId: "sf-papillomavirus", scoreBoost: 18 },
    { keyword: "vaccin papillomavirus", resourceId: "sf-papillomavirus", scoreBoost: 22 },
    { keyword: "vaccination papillomavirus", resourceId: "sf-papillomavirus", scoreBoost: 22 },
    { keyword: "vaccin hpv", resourceId: "sf-papillomavirus", scoreBoost: 22 },
    { keyword: "vaccination hpv", resourceId: "sf-papillomavirus", scoreBoost: 22 },
    { keyword: "vaccination 5eme", resourceId: "sf-papillomavirus", scoreBoost: 18 },
    { keyword: "vaccination 5e", resourceId: "sf-papillomavirus", scoreBoost: 18 },
    { keyword: "campagne scolaire vaccination", resourceId: "sf-papillomavirus", scoreBoost: 16 },
    { keyword: "cancer du col de l uterus", resourceId: "sf-papillomavirus", scoreBoost: 18 },
    { keyword: "col de l uterus", resourceId: "sf-papillomavirus", scoreBoost: 14 },

    { keyword: "canicule", resourceId: "sf-canicule", scoreBoost: 18 },
    { keyword: "fortes chaleurs", resourceId: "sf-canicule", scoreBoost: 18 },
    { keyword: "forte chaleur", resourceId: "sf-canicule", scoreBoost: 16 },
    { keyword: "coup de chaleur", resourceId: "sf-canicule", scoreBoost: 18 },
    { keyword: "coup de chaud", resourceId: "sf-canicule", scoreBoost: 18 },
    { keyword: "vague de chaleur", resourceId: "sf-canicule", scoreBoost: 18 },
    { keyword: "deshydratation", resourceId: "sf-canicule", scoreBoost: 12 },
    { keyword: "registre canicule", resourceId: "sf-canicule", scoreBoost: 22 },
    { keyword: "j ai trop chaud", resourceId: "sf-canicule", scoreBoost: 14 },
    { keyword: "il fait trop chaud", resourceId: "sf-canicule", scoreBoost: 14 },

    { keyword: "chute", resourceId: "sf-chute-personne-agee", scoreBoost: 12 },
    { keyword: "chutes", resourceId: "sf-chute-personne-agee", scoreBoost: 12 },
    { keyword: "prevenir les chutes", resourceId: "sf-chute-personne-agee", scoreBoost: 20 },
    { keyword: "prevention des chutes", resourceId: "sf-chute-personne-agee", scoreBoost: 20 },
    { keyword: "chute personne agee", resourceId: "sf-chute-personne-agee", scoreBoost: 22 },
    { keyword: "chute personne âgée", resourceId: "sf-chute-personne-agee", scoreBoost: 22 },
    { keyword: "personne agee qui tombe", resourceId: "sf-chute-personne-agee", scoreBoost: 18 },
    { keyword: "ma grand mere est tombee", resourceId: "sf-chute-personne-agee", scoreBoost: 18 },
    { keyword: "mon grand pere est tombe", resourceId: "sf-chute-personne-agee", scoreBoost: 18 },
    { keyword: "perte d equilibre", resourceId: "sf-chute-personne-agee", scoreBoost: 14 },
    { keyword: "risque de chute", resourceId: "sf-chute-personne-agee", scoreBoost: 16 },
    { keyword: "plan anti chute", resourceId: "sf-chute-personne-agee", scoreBoost: 16 },

    { keyword: "sante voyage", resourceId: "sf-sante-voyage", scoreBoost: 22 },
    { keyword: "sante du voyageur", resourceId: "sf-sante-voyage", scoreBoost: 22 },
    { keyword: "preparer un voyage", resourceId: "sf-sante-voyage", scoreBoost: 20 },
    { keyword: "preparation voyage", resourceId: "sf-sante-voyage", scoreBoost: 18 },
    { keyword: "vaccin voyage", resourceId: "sf-sante-voyage", scoreBoost: 22 },
    { keyword: "vaccination voyage", resourceId: "sf-sante-voyage", scoreBoost: 22 },
    { keyword: "trousse de secours voyage", resourceId: "sf-sante-voyage", scoreBoost: 22 },
    { keyword: "trousse medicale voyage", resourceId: "sf-sante-voyage", scoreBoost: 22 },
    { keyword: "assurance voyage", resourceId: "sf-sante-voyage", scoreBoost: 18 },
    { keyword: "rapatriement sanitaire", resourceId: "sf-sante-voyage", scoreBoost: 20 },
    { keyword: "paludisme", resourceId: "sf-sante-voyage", scoreBoost: 20 },
    { keyword: "fievre jaune", resourceId: "sf-sante-voyage", scoreBoost: 18 },
    { keyword: "moustique voyage", resourceId: "sf-sante-voyage", scoreBoost: 18 },
    { keyword: "eau potable voyage", resourceId: "sf-sante-voyage", scoreBoost: 20 },
    { keyword: "purifier eau voyage", resourceId: "sf-sante-voyage", scoreBoost: 20 },
    { keyword: "diarrhee du voyageur", resourceId: "sf-sante-voyage", scoreBoost: 20 },
    { keyword: "phlebite avion", resourceId: "sf-sante-voyage", scoreBoost: 22 },
    { keyword: "vol long courrier", resourceId: "sf-sante-voyage", scoreBoost: 16 },
    { keyword: "mal des montagnes", resourceId: "sf-sante-voyage", scoreBoost: 22 },
    { keyword: "mal aigu des montagnes", resourceId: "sf-sante-voyage", scoreBoost: 22 },
    { keyword: "altitude voyage", resourceId: "sf-sante-voyage", scoreBoost: 18 },
    { keyword: "jet lag", resourceId: "sf-sante-voyage", scoreBoost: 22 },
    { keyword: "decalage horaire", resourceId: "sf-sante-voyage", scoreBoost: 20 },
    { keyword: "voyager enceinte", resourceId: "sf-sante-voyage", scoreBoost: 22 },
    { keyword: "voyage grossesse", resourceId: "sf-sante-voyage", scoreBoost: 20 },
    { keyword: "voyage avec enfant", resourceId: "sf-sante-voyage", scoreBoost: 20 },
    { keyword: "voyager avec enfant", resourceId: "sf-sante-voyage", scoreBoost: 20 },
    { keyword: "voyage personne agee", resourceId: "sf-sante-voyage", scoreBoost: 20 },
    { keyword: "personne agee voyage", resourceId: "sf-sante-voyage", scoreBoost: 20 },

    { keyword: "actions outils", resourceId: "pro-actions-outils", scoreBoost: 12 },
    { keyword: "ressources professionnels", resourceId: "pro-actions-outils", scoreBoost: 12 },
    { keyword: "outils pro", resourceId: "pro-actions-outils", scoreBoost: 10 },
    { keyword: "dispositifs du territoire", resourceId: "pro-dispositifs-territoire", scoreBoost: 18 },
    { keyword: "dispositif sante territoire", resourceId: "pro-dispositifs-territoire", scoreBoost: 16 },
    { keyword: "ressources professionnelles cpts", resourceId: "pro-dispositifs-territoire", scoreBoost: 14 },
    { keyword: "outils du territoire", resourceId: "pro-dispositifs-territoire", scoreBoost: 14 },
    { keyword: "dispositifs cpts", resourceId: "pro-dispositifs-territoire", scoreBoost: 16 },
    { keyword: "orientation psychiatrie", resourceId: "pro-dispositifs-territoire", scoreBoost: 16 },
    { keyword: "rcp psy", resourceId: "pro-dispositifs-territoire", scoreBoost: 16 },

    { keyword: "supports", resourceId: "pro-supports", scoreBoost: 11 },
    { keyword: "commande support", resourceId: "pro-supports", scoreBoost: 12 },
    { keyword: "coordinatrice", resourceId: "pro-supports" },
    { keyword: "imprimer", resourceId: "pro-supports" },
    { keyword: "livrer", resourceId: "pro-supports" },

    { keyword: "formation", resourceId: "pro-formations", scoreBoost: 12 },
    { keyword: "formations", resourceId: "pro-formations", scoreBoost: 12 },
    { keyword: "inscription", resourceId: "pro-formations", scoreBoost: 8 },
    { keyword: "formation a venir", resourceId: "pro-formations", scoreBoost: 10 },
    { keyword: "adherer", resourceId: "pro-adhesion", scoreBoost: 12 },
    { keyword: "adhesion", resourceId: "pro-adhesion", scoreBoost: 12 },
    { keyword: "devenir adherent", resourceId: "pro-adhesion", scoreBoost: 12 },
    { keyword: "adhesion professionnel", resourceId: "pro-adhesion", scoreBoost: 12 },
    { keyword: "aderer", resourceId: "pro-adhesion", scoreBoost: 12 },

    { keyword: "formulaire mas", resourceId: "ao-formulaire-mas", scoreBoost: 10 },
    { keyword: "pharmacies participantes", resourceId: "ao-affiche-pharmacies", scoreBoost: 10 },
    { keyword: "livret mss", resourceId: "ao-livret-mss", scoreBoost: 10 },
    { keyword: "pole etp", resourceId: "ao-poletp", scoreBoost: 10 },
    { keyword: "maison nutrition", resourceId: "ao-maison-nutrition", scoreBoost: 10 },
    { keyword: "medprev", resourceId: "ao-medprev", scoreBoost: 10 },
    { keyword: "mots", resourceId: "ao-mots", scoreBoost: 8 },
    { keyword: "burn out", resourceId: "sante-mentale", scoreBoost: 10 },
    { keyword: "epuisement soignant", resourceId: "ao-mots", scoreBoost: 10 },

    { keyword: "faq", resourceId: "faq", scoreBoost: 7 },
  ],
  nodes: {
    start: {
      id: "start",
      message:
        "Bonjour, je peux vous aider à trouver la ressource CPTS adaptée. Choisissez une option ou écrivez votre demande.",
      quickReplies: mainQuickReplies,
    },
    "start-error": {
      id: "start-error",
      message:
        "Vous semblez vous être perdu. Je peux vous aider à retrouver votre chemin. Que cherchez-vous ?",
      quickReplies: errorPageQuickReplies,
    },
    "medecin-traitant": {
      id: "medecin-traitant",
      message: "Quelle est votre situation ?",
      quickReplies: [
        {
          id: "qr-medecin-traitant-chercher",
          label: "Je cherche un médecin traitant",
          value: "je cherche un medecin traitant",
          nextNodeId: "medecin-traitant-chercher",
        },
        {
          id: "qr-medecin-traitant-changer",
          label: "Je veux changer de médecin",
          value: "je veux changer de medecin",
          nextNodeId: "medecin-traitant-changer",
        },
        {
          id: "qr-medecin-traitant-indisponible",
          label: "Mon médecin n'est plus disponible",
          value: "mon medecin n est plus disponible",
          nextNodeId: "medecin-traitant-indisponible",
        },
        restartQuickReply,
      ],
      actions: [
        {
          type: "suggest_resources",
          resourceIds: ["patients-medecin-traitant", "medecin-traitant", "coordonnees"],
        },
      ],
    },
    "medecin-traitant-chercher": {
      id: "medecin-traitant-chercher",
      message: "Voici les ressources utiles pour trouver un médecin traitant :",
      actions: [
        {
          type: "suggest_resources",
          resourceIds: ["patients-medecin-traitant", "medecin-traitant", "coordonnees"],
        },
      ],
    },
    "medecin-traitant-changer": {
      id: "medecin-traitant-changer",
      message: "Vous pouvez changer de médecin traitant à tout moment. Voici comment faire :",
      actions: [
        {
          type: "suggest_resources",
          resourceIds: ["patients-medecin-traitant", "medecin-traitant", "coordonnees"],
        },
      ],
    },
    "medecin-traitant-indisponible": {
      id: "medecin-traitant-indisponible",
      message: "En attendant de trouver un nouveau médecin traitant :",
      actions: [
        {
          type: "suggest_resources",
          resourceIds: ["patients-medecin-traitant", "medecin-traitant", "coordonnees"],
        },
      ],
    },
    urgences: {
      id: "urgences",
      message: "De quel type d'aide avez-vous besoin ?",
      quickReplies: [
        {
          id: "qr-urgence-medicale",
          label: "Urgence médicale",
          value: "urgence medicale",
          nextNodeId: "urgence-medicale",
        },
        {
          id: "qr-medecin-garde",
          label: "Médecin de garde",
          value: "medecin de garde",
          nextNodeId: "medecin-garde",
        },
        {
          id: "qr-pharmacie-garde",
          label: "Pharmacie de garde",
          value: "pharmacie de garde",
          nextNodeId: "pharmacie-garde",
        },
        restartQuickReply,
      ],
    },
    "urgence-medicale": {
      id: "urgence-medicale",
      message: "Appelez le 15 (SAMU) ou le 112.",
      actions: [
        {
          type: "suggest_resources",
          resourceIds: ["urgence-15", "coordonnees", "urgence-3114"],
        },
      ],
    },
    "symptomes-douleur": {
      id: "symptomes-douleur",
      message:
        "Pour toute douleur ou symptôme physique, votre médecin traitant est le bon interlocuteur. Si la douleur est intense, soudaine ou inquiétante, contactez le 15 (SAMU). En cas de doute, vous pouvez aussi consulter une pharmacie de garde.",
      quickReplies: [
        {
          id: "qr-symptomes-douleur-sans-medecin",
          label: "Je n'ai pas de médecin traitant",
          value: "je n ai pas de medecin traitant",
          nextNodeId: "medecin-traitant",
        },
        {
          id: "qr-symptomes-douleur-retour",
          label: "Retour menu",
          value: "retour menu",
          nextNodeId: "start",
        },
      ],
      actions: [
        {
          type: "suggest_resources",
          resourceIds: ["medecin-traitant", "urgence-15", "pharmacie-garde"],
        },
      ],
    },
    "urgence-medicale-suspecte": {
      id: "urgence-medicale-suspecte",
      message:
        "Une douleur thoracique peut nécessiter une prise en charge urgente. Appelez le 15 (SAMU) sans attendre. En cas de doute, contactez aussi votre médecin traitant.",
      actions: [
        {
          type: "suggest_resources",
          resourceIds: ["urgence-15", "medecin-traitant"],
        },
      ],
    },
    "medecin-garde": {
      id: "medecin-garde",
      message: "Pour joindre un médecin de garde ou une consultation non programmée :",
      actions: [
        {
          type: "suggest_resources",
          resourceIds: ["coordonnees", "annuaire"],
        },
      ],
    },
    "pharmacie-garde": {
      id: "pharmacie-garde",
      message: "Pour trouver une pharmacie de garde :",
      actions: [
        {
          type: "suggest_resources",
          resourceIds: ["pharmacie-garde", "coordonnees"],
        },
      ],
    },
    "sante-mentale": {
      id: "sante-mentale",
      message: "Comment puis-je vous orienter ?",
      quickReplies: [
        {
          id: "qr-sante-mentale-psychologue",
          label: "Je cherche un psychologue",
          value: "je cherche un psychologue",
          nextNodeId: "sante-mentale-psychologue",
        },
        {
          id: "qr-sante-mentale-difficile",
          label: "Je traverse une période difficile",
          value: "je traverse une periode difficile",
          nextNodeId: "sante-mentale-difficile",
        },
        {
          id: "qr-sante-mentale-enfant",
          label: "Pour mon enfant / adolescent",
          value: "pour mon enfant adolescent",
          nextNodeId: "sante-mentale-enfant",
        },
        {
          id: "qr-sante-mentale-articles",
          label: "Articles & ressources",
          value: "articles et ressources",
          nextNodeId: "sante-mentale-articles",
        },
        restartQuickReply,
      ],
    },
    "sante-mentale-psychologue": {
      id: "sante-mentale-psychologue",
      message: "Pour trouver un psychologue ou une ressource adaptée :",
      actions: [
        {
          type: "suggest_resources",
          resourceIds: ["sante-mentale-annuaire", "sante-mentale", "ao-questions-psy"],
        },
      ],
    },
    "sante-mentale-difficile": {
      id: "sante-mentale-difficile",
      message:
        "Je suis désolé que vous traversiez cela. En cas de danger immédiat, appelez le 17 (police) ou le 15. Le 3919 (violences) et le 3114 (prévention suicide) sont disponibles 24h/24, 7j/7.",
      actions: [
        {
          type: "suggest_resources",
          message: "En urgence, vous pouvez joindre :",
          resourceIds: ["urgence-3919", "urgence-17", "urgence-3114"],
        },
        {
          type: "suggest_resources",
          message: "Pour une écoute ou une orientation :",
          resourceIds: ["sm-face-aux-violences", "sante-mentale", "sante-mentale-annuaire"],
        },
      ],
    },
    "sante-mentale-enfant": {
      id: "sante-mentale-enfant",
      message: "Pour un enfant ou un adolescent, voici les ressources les plus adaptées :",
      actions: [
        {
          type: "suggest_resources",
          resourceIds: ["sante-mentale-jeunes", "sante-mentale", "sante-mentale-annuaire"],
        },
      ],
    },
    "sante-mentale-articles": {
      id: "sante-mentale-articles",
      message: "Voici les articles disponibles sur la santé mentale.",
      quickReplies: [
        {
          id: "qr-sante-mentale-articles-jeunes",
          label: "Santé mentale des jeunes",
          value: "sante mentale des jeunes",
          actionResourceIds: ["sante-mentale-jeunes"],
        },
        {
          id: "qr-sante-mentale-articles-pro",
          label: "Professionnels & approches",
          value: "professionnels et approches",
          actionResourceIds: ["sm-pro-approches"],
        },
        {
          id: "qr-sante-mentale-articles-insomnie",
          label: "Insomnie",
          value: "insomnie",
          actionResourceIds: ["sf-insomnie"],
        },
        {
          id: "qr-sante-mentale-articles-apnee",
          label: "Apnée du sommeil",
          value: "apnee du sommeil",
          actionResourceIds: ["etp-apnee-sommeil"],
        },
        {
          id: "qr-sante-mentale-articles-retour",
          label: "Retour menu santé mentale",
          value: "retour sante mentale",
          nextNodeId: "sante-mentale",
        },
      ],
    },
    annuaire: {
      id: "annuaire",
      message: "Pour trouver un professionnel de santé :",
      quickReplies: [restartQuickReply],
      actions: [
        {
          type: "suggest_resources",
          resourceIds: ["annuaire"],
        },
      ],
    },
    "presentation-node": {
      id: "presentation-node",
      message: "Pour comprendre la CPTS et ses missions :",
      quickReplies: [restartQuickReply],
      actions: [
        {
          type: "suggest_resources",
          resourceIds: ["presentation"],
        },
      ],
    },
    "mon-espace-sante-node": {
      id: "mon-espace-sante-node",
      message: "Voici la page dédiée à l'utilisation de Mon Espace Santé :",
      quickReplies: [restartQuickReply],
      actions: [
        {
          type: "suggest_resources",
          resourceIds: ["mon-espace-sante"],
        },
      ],
    },
    professionnels: {
      id: "professionnels",
      message: "Voici les principales ressources pour les professionnels :",
      quickReplies: [restartQuickReply],
      actions: [
        {
          type: "suggest_resources",
          resourceIds: ["pro-actions-outils", "pro-supports", "pro-formations"],
        },
      ],
    },
    "documents-role-check": {
      id: "documents-role-check",
      message: "Êtes-vous professionnel de santé ? Cela me permet de vous orienter vers les bons documents.",
      quickReplies: [
        {
          id: "qr-docs-pro-oui",
          label: "Oui, je suis professionnel",
          value: "professionnel",
          nextNodeId: "documents-pro",
        },
        {
          id: "qr-docs-pro-non",
          label: "Non, je suis patient",
          value: "patient",
          nextNodeId: "documents-patient",
        },
        {
          id: "qr-docs-retour-fallback",
          label: "Retour menu fallback",
          value: "retour menu fallback",
          nextNodeId: "fallback",
        },
      ],
    },
    "documents-pro": {
      id: "documents-pro",
      message:
        "Voici les outils et documents pour les professionnels de santé. L'accès nécessite une connexion à votre compte professionnel.",
      quickReplies: [
        {
          id: "qr-docs-pro-questionnaires",
          label: "Questionnaires médecin traitant",
          value: "questionnaires medecin traitant",
          actionResourceIds: ["ao-questionnaire-medecin", "ao-questionnaire-paramedical"],
        },
        {
          id: "qr-docs-pro-mas",
          label: "Formulaire MAS",
          value: "formulaire mas",
          actionResourceIds: ["ao-formulaire-mas"],
        },
        {
          id: "qr-docs-pro-supports",
          label: "Supports CPTS pour pros",
          value: "supports cpts pour pros",
          actionResourceIds: ["pro-supports"],
        },
        {
          id: "qr-docs-pro-dispositifs",
          label: "Dispositifs du territoire",
          value: "dispositifs du territoire",
          actionResourceIds: ["pro-dispositifs-territoire"],
        },
        {
          id: "qr-docs-pro-espace",
          label: "Voir l'espace professionnels",
          value: "voir espace professionnels",
          actionResourceIds: ["espace-pro"],
        },
        {
          id: "qr-docs-pro-adhesion",
          label: "Adhérer à la CPTS",
          value: "adherer a la cpts",
          actionResourceIds: ["pro-adhesion"],
        },
        {
          id: "qr-docs-pro-formations",
          label: "Formations",
          value: "formations",
          actionResourceIds: ["pro-formations"],
        },
        {
          id: "qr-docs-pro-retour-fallback",
          label: "Retour menu fallback",
          value: "retour menu fallback",
          nextNodeId: "fallback",
        },
      ],
    },
    "documents-patient": {
      id: "documents-patient",
      message:
        "Les outils de coordination interne sont réservés aux professionnels et nécessitent une authentification. Voici les documents et ressources accessibles à tous :",
      quickReplies: [
        {
          id: "qr-docs-patient-memos",
          label: "Mémos suivi de maladies chroniques",
          value: "memos suivi de maladies chroniques",
          actionResourceIds: ["memos-suivi"],
        },
        {
          id: "qr-docs-patient-annuaire-sm",
          label: "Annuaire santé mentale",
          value: "annuaire sante mentale",
          actionResourceIds: ["sante-mentale-annuaire"],
        },
        {
          id: "qr-docs-patient-prevention",
          label: "Articles de prévention",
          value: "articles de prevention",
          actionResourceIds: ["prevention-familiale"],
        },
        {
          id: "qr-docs-patient-faq",
          label: "FAQ patients",
          value: "faq patients",
          actionResourceIds: ["faq"],
        },
        {
          id: "qr-docs-patient-medecin",
          label: "Trouver un médecin",
          value: "trouver un medecin",
          actionResourceIds: ["medecin-traitant"],
        },
        {
          id: "qr-docs-patient-espace-sante",
          label: "Mon Espace Santé",
          value: "mon espace sante",
          actionResourceIds: ["mon-espace-sante"],
        },
        {
          id: "qr-docs-patient-tuto-espace-sante",
          label: "Tutoriel Mon Espace Santé",
          value: "tutoriel mon espace sante",
          actionResourceIds: ["patients-tuto-espace-sante"],
        },
        {
          id: "qr-docs-patient-contact",
          label: "Contacter la CPTS",
          value: "contacter la cpts",
          actionResourceIds: ["contact-email"],
        },
        {
          id: "qr-docs-patient-retour-fallback",
          label: "Retour menu fallback",
          value: "retour menu fallback",
          nextNodeId: "fallback",
        },
      ],
    },
    supports: {
      id: "supports",
      message: "Pour commander des supports, utilisez cette page :",
      quickReplies: [restartQuickReply],
      actions: [
        {
          type: "suggest_resources",
          resourceIds: ["pro-supports", "contact-email"],
        },
      ],
    },
    formations: {
      id: "formations",
      message: "Pour consulter les formations et vous inscrire :",
      quickReplies: [restartQuickReply],
      actions: [
        {
          type: "suggest_resources",
          resourceIds: ["pro-formations", "pro-actions-outils"],
        },
      ],
    },
    prevention: {
      id: "prevention",
      message: "Quel sujet de prévention souhaitez-vous explorer ?",
      quickReplies: [
        {
          id: "qr-prevention-vaccinations",
          label: "Vaccinations",
          value: "vaccinations",
          nextNodeId: "prevention-vaccinations",
        },
        {
          id: "qr-prevention-depistages",
          label: "Dépistages cancers",
          value: "depistages cancers",
          nextNodeId: "prevention-depistages",
        },
        {
          id: "qr-prevention-sommeil",
          label: "Sommeil",
          value: "sommeil",
          nextNodeId: "prevention-sommeil",
        },
        {
          id: "qr-prevention-chroniques",
          label: "Suivi maladies chroniques",
          value: "suivi maladies chroniques",
          actionResourceIds: ["memos-suivi"],
        },
        {
          id: "qr-prevention-quotidien",
          label: "Prévention au quotidien",
          value: "prevention quotidien",
          nextNodeId: "prevention-quotidien",
        },
        {
          id: "qr-prevention-hub",
          label: "Voir tout le hub prévention",
          value: "hub prevention",
          actionResourceIds: ["prevention-familiale"],
        },
        restartQuickReply,
      ],
    },
    "prevention-vaccinations": {
      id: "prevention-vaccinations",
      message: "Voici les campagnes de vaccination en cours sur notre territoire.",
      quickReplies: [
        {
          id: "qr-prevention-vac-grippe",
          label: "Vaccination antigrippale",
          value: "vaccination antigrippale",
          actionResourceIds: ["sf-vaccination-grippe-2025"],
        },
        {
          id: "qr-prevention-vac-covid",
          label: "Vaccination anti-COVID",
          value: "vaccination anti covid",
          actionResourceIds: ["sf-vaccination-covid-2025"],
        },
        {
          id: "qr-prevention-vac-hpv",
          label: "Vaccination papillomavirus (HPV)",
          value: "vaccination papillomavirus",
          actionResourceIds: ["sf-papillomavirus"],
        },
        {
          id: "qr-prevention-vac-retour",
          label: "Retour menu prévention",
          value: "retour prevention",
          nextNodeId: "prevention",
        },
      ],
    },
    "prevention-depistages": {
      id: "prevention-depistages",
      message: "Voici les campagnes de dépistage de cancers.",
      quickReplies: [
        {
          id: "qr-prevention-dep-sein",
          label: "Cancer du sein (Octobre Rose)",
          value: "cancer du sein octobre rose",
          actionResourceIds: ["sf-octobre-rose-2025"],
        },
        {
          id: "qr-prevention-dep-colorectal",
          label: "Cancer colorectal (Mars Bleu)",
          value: "cancer colorectal mars bleu",
          actionResourceIds: ["sf-mars-bleu-2026"],
        },
        {
          id: "qr-prevention-dep-masculine",
          label: "Santé masculine (Movember)",
          value: "sante masculine movember",
          actionResourceIds: ["sf-movember-2026"],
        },
        {
          id: "qr-prevention-dep-retour",
          label: "Retour menu prévention",
          value: "retour prevention",
          nextNodeId: "prevention",
        },
      ],
    },
    "prevention-sommeil": {
      id: "prevention-sommeil",
      message: "Voici nos ressources sur les troubles du sommeil.",
      quickReplies: [
        {
          id: "qr-prevention-sommeil-insomnie",
          label: "Insomnie",
          value: "insomnie",
          actionResourceIds: ["sf-insomnie"],
        },
        {
          id: "qr-prevention-sommeil-apnee",
          label: "Apnée du sommeil",
          value: "apnee du sommeil",
          actionResourceIds: ["etp-apnee-sommeil"],
        },
        {
          id: "qr-prevention-sommeil-retour",
          label: "Retour menu prévention",
          value: "retour prevention",
          nextNodeId: "prevention",
        },
      ],
    },
    "prevention-quotidien": {
      id: "prevention-quotidien",
      message: "Voici nos conseils de prévention pour le quotidien.",
      quickReplies: [
        {
          id: "qr-prevention-quotidien-canicule",
          label: "Canicule et fortes chaleurs",
          value: "canicule",
          actionResourceIds: ["sf-canicule"],
        },
        {
          id: "qr-prevention-quotidien-chute",
          label: "Prévenir les chutes (personnes âgées)",
          value: "prevenir les chutes",
          actionResourceIds: ["sf-chute-personne-agee"],
        },
        {
          id: "qr-prevention-quotidien-voyage",
          label: "Santé en voyage",
          value: "sante voyage",
          actionResourceIds: ["sf-sante-voyage"],
        },
        {
          id: "qr-prevention-quotidien-retour",
          label: "Retour menu prévention",
          value: "retour prevention",
          nextNodeId: "prevention",
        },
      ],
    },
    faq: {
      id: "faq",
      message: "Vous pouvez commencer par la FAQ, puis nous écrire si nécessaire :",
      quickReplies: [restartQuickReply],
      actions: [
        {
          type: "suggest_resources",
          resourceIds: ["faq", "contact-email"],
        },
      ],
    },
    fallback: {
      id: "fallback",
      message: "Je n'ai pas bien compris votre demande. Voici quelques pistes pour vous aider à trouver ce que vous cherchez :",
      quickReplies: [
        {
          id: "qr-fallback-pro",
          label: "Je cherche un professionnel de santé",
          value: "professionnel sante",
          nextNodeId: "medecin-traitant",
        },
        {
          id: "qr-fallback-sante-mentale",
          label: "J'ai une question sur la santé mentale",
          value: "question sante mentale",
          nextNodeId: "sante-mentale",
        },
        {
          id: "qr-fallback-prevention",
          label: "Je veux une information de prévention",
          value: "information prevention",
          nextNodeId: "prevention",
        },
        {
          id: "qr-fallback-document",
          label: "Je cherche un document",
          value: "chercher document",
          nextNodeId: "documents-role-check",
        },
        {
          id: "qr-fallback-urgence",
          label: "J'ai une urgence",
          value: "urgence",
          nextNodeId: "urgences",
        },
        {
          id: "qr-fallback-contact",
          label: "Contacter la CPTS",
          value: "contacter cpts",
          actionResourceIds: ["contact-email", "coordonnees"],
        },
        restartQuickReply,
      ],
    },
  },
  rules: {
    startNodeId: "start",
    fallbackNodeId: "fallback",
    restartNodeId: "start",
    maxSuggestions: 3,
    minScore: 48,
    fuzzyDistanceThreshold: 1,
    decisionRules: [
      {
        id: "rule-quick-reply-text",
        trigger: "quick_reply_text",
        description: "Si le texte correspond à un choix rapide, suivre sa transition.",
      },
      {
        id: "rule-keyword",
        trigger: "keyword_detected",
        description: "Si un mot-clé est détecté, proposer les 3 meilleures ressources.",
      },
      {
        id: "rule-fallback",
        trigger: "no_match",
        description: "Si aucun match, afficher les catégories et suggérer une reformulation.",
      },
    ],
  },
}
